apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zgsdk9ndm-java-quarkus
  janus-idp.io/tekton: zgsdk9ndm-java-quarkus
  backstage.io/kubernetes-id: zgsdk9ndm-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zgsdk9ndm-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
